### ISSUE TITLE
run tests against redis 4 - fails with TypeError: no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by pravi** [tpitale/mail_room#102]
```
Failures:

  1) MailRoom::Delivery::Sidekiq#options when sentinel is specified client has same specified sentinel params
     Failure/Error: expect(redis.client.instance_variable_get(:@connector)).to be_a Redis::Client::Connector::Sentinel

     TypeError:
       no implicit conversion of Symbol into Integer
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:346:in `establish_connection'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:106:in `block in connect'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:306:in `with_reconnect'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:105:in `connect'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:381:in `ensure_connected'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:231:in `block in process'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:319:in `logging'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:230:in `process'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:125:in `call'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis.rb:222:in `block in client'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis.rb:52:in `block in synchronize'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis.rb:52:in `synchronize'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis.rb:221:in `client'
     # ./spec/lib/delivery/sidekiq_spec.rb:68:in `block (4 levels) in <top (required)>'

  2) MailRoom::Arbitration::Redis redis client connection params when sentinel is present client has same specified sentinel params
     Failure/Error: expect(client.client.instance_variable_get(:@connector)).to be_a Redis::Client::Connector::Sentinel

     TypeError:
       no implicit conversion of Symbol into Integer
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:346:in `establish_connection'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:106:in `block in connect'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:306:in `with_reconnect'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:105:in `connect'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:381:in `ensure_connected'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:231:in `block in process'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:319:in `logging'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:230:in `process'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis/client.rb:125:in `call'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis.rb:222:in `block in client'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis.rb:52:in `block in synchronize'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis.rb:52:in `synchronize'
     # /usr/share/rubygems-integration/all/gems/redis-4.1.2/lib/redis.rb:221:in `client'
     # ./spec/lib/arbitration/redis_spec.rb:120:in `block (4 levels) in <top (required)>'

Finished in 0.0533 seconds (files took 0.35497 seconds to load)
51 examples, 2 failures

Failed examples:

rspec ./spec/lib/delivery/sidekiq_spec.rb:67 # MailRoom::Delivery::Sidekiq#options when sentinel is specified client has same specified sentinel params
rspec ./spec/lib/arbitration/redis_spec.rb:119 # MailRoom::Arbitration::Redis redis client connection params when sentinel is present client has same specified sentinel params

Randomized with seed 3049
```

**Comment by tpitale** [comment]
Sentinel support in gems and testing abilities is not very good.
