### ISSUE TITLE
Console Log

### ISSUE THREAD

**Issue by clairton** [tpitale/mail_room#142]
Hi

I try a postback delivery_method, with this config to show log in stdout with version 0.10.0 and ruby 3.1.2p2:

```yml
---
:mailboxes:
  -
    ...
    :delivery_method: postback
    :logger:
      :log_path: :stdout
    ....
  ```
But I Have this error:

```bash
/usr/local/lib/ruby/3.1.0/logger/log_device.rb:95:in `initialize': no implicit conversion of Symbol into String (TypeError)
	from /usr/local/lib/ruby/3.1.0/logger/log_device.rb:95:in `open'
	from /usr/local/lib/ruby/3.1.0/logger/log_device.rb:95:in `open_logfile'
	from /usr/local/lib/ruby/3.1.0/logger/log_device.rb:86:in `set_dev'
	from /usr/local/lib/ruby/3.1.0/logger/log_device.rb:18:in `initialize'
	from /usr/local/lib/ruby/3.1.0/logger.rb:390:in `new'
	from /usr/local/lib/ruby/3.1.0/logger.rb:390:in `initialize'
	from /usr/local/bundle/gems/mail_room-0.10.0/lib/mail_room/mailbox.rb:76:in `new'
	from /usr/local/bundle/gems/mail_room-0.10.0/lib/mail_room/mailbox.rb:76:in `logger'
	from /usr/local/bundle/gems/mail_room-0.10.0/lib/mail_room/mailbox_watcher.rb:44:in `quit'
	from /usr/local/bundle/gems/mail_room-0.10.0/lib/mail_room/coordinator.rb:30:in `each'
	from /usr/local/bundle/gems/mail_room-0.10.0/lib/mail_room/coordinator.rb:30:in `quit'
	from /usr/local/bundle/gems/mail_room-0.10.0/lib/mail_room/coordinator.rb:25:in `ensure in run'
	from /usr/local/bundle/gems/mail_room-0.10.0/lib/mail_room/coordinator.rb:25:in `run'
	from /usr/local/bundle/gems/mail_room-0.10.0/lib/mail_room/cli.rb:52:in `start'
	from /usr/local/bundle/gems/mail_room-0.10.0/bin/mail_room:5:in `<top (required)>'
	from /usr/local/bundle/bin/mail_room:25:in `load'
	from /usr/local/bundle/bin/mail_room:25:in `<main>'
/usr/local/lib/ruby/3.1.0/logger/log_device.rb:95:in `initialize': no implicit conversion of Symbol into String (TypeError)
	from /usr/local/lib/ruby/3.1.0/logger/log_device.rb:95:in `open'
	from /usr/local/lib/ruby/3.1.0/logger/log_device.rb:95:in `open_logfile'
	from /usr/local/lib/ruby/3.1.0/logger/log_device.rb:86:in `set_dev'
	from /usr/local/lib/ruby/3.1.0/logger/log_device.rb:18:in `initialize'
	from /usr/local/lib/ruby/3.1.0/logger.rb:390:in `new'
	from /usr/local/lib/ruby/3.1.0/logger.rb:390:in `initialize'
	from /usr/local/bundle/gems/mail_room-0.10.0/lib/mail_room/mailbox.rb:76:in `new'
	from /usr/local/bundle/gems/mail_room-0.10.0/lib/mail_room/mailbox.rb:76:in `logger'
	from /usr/local/bundle/gems/mail_room-0.10.0/lib/mail_room/mailbox_watcher.rb:26:in `run'
	from /usr/local/bundle/gems/mail_room-0.10.0/lib/mail_room/coordinator.rb:19:in `each'
	from /usr/local/bundle/gems/mail_room-0.10.0/lib/mail_room/coordinator.rb:19:in `run'
	from /usr/local/bundle/gems/mail_room-0.10.0/lib/mail_room/cli.rb:52:in `start'
	from /usr/local/bundle/gems/mail_room-0.10.0/bin/mail_room:5:in `<top (required)>'
	from /usr/local/bundle/bin/mail_room:25:in `load'
	from /usr/local/bundle/bin/mail_room:25:in `<main>'
```

If I fill de `log_path` with `STDOUT` it works, but puts the log at stdout file

Anyone can me help?

**Comment by tpitale** [comment]
This was added in v0.10.1 I think: https://github.com/tpitale/mail_room/commit/46f9ce3188a38dfd1cf6ac2590555f5b0e579ddf

**Comment by clairton** [comment]
Thank's for answered @tpitale but the logs puts in file STDOUT with this way =(

**Comment by tpitale** [comment]
You said you were using 0.10.0. That was before STDOUT was supported.
