### ISSUE TITLE
Handle EOFError

### ISSUE THREAD

**Issue by tpitale** [tpitale/mail_room#15]
```
/Users/Mac/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/imap.rb:1150:in `get_tagged_response': end of file reached (EOFError)
from /Users/Mac/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/imap.rb:1210:in `block in send_command'
from /Users/Mac/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
from /Users/Mac/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/imap.rb:1192:in `send_command'
from /Users/Mac/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/imap.rb:1345:in `block in search_internal'
from /Users/Mac/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
from /Users/Mac/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/imap.rb:1341:in `search_internal'
from /Users/Mac/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/imap.rb:768:in `search'
from /Users/Mac/Desktop/mail_room/lib/mail_room/mailbox_handler.rb:39:in `new_message_ids'
from /Users/Mac/Desktop/mail_room/lib/mail_room/mailbox_handler.rb:29:in `new_messages'
from /Users/Mac/Desktop/mail_room/lib/mail_room/mailbox_handler.rb:17:in `process'
from /Users/Mac/Desktop/mail_room/lib/mail_room/mailbox_watcher.rb:152:in `process_mailbox'
from /Users/Mac/Desktop/mail_room/lib/mail_room/mailbox_watcher.rb:129:in `block in run'
```

**Comment by tbreier** [comment]
First of all, thank you @tpitale for this gem! :smile: 

Second, I have seen this error appear as well. I am not able to reproduce it either though...

**Comment by tpitale** [comment]
Thanks for reporting @tbreier! I'll try to implement what I proposed doing shortly. How does that work for you?

**Comment by tbreier** [comment]
Sure, no problem!

I hadn't attached my stacktrace, but it's the same as posted above:
```
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/imap.rb:1150:in `get_tagged_response': end of file reached (EOFError)
        from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/imap.rb:1210:in `block in send_command'
        from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/imap.rb:1192:in `send_command'
        from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/imap.rb:1345:in `block in search_internal'
        from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/imap.rb:1341:in `search_internal'
        from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/imap.rb:768:in `search'
        from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mail_room-0.3.0/lib/mail_room/mailbox_handler.rb:39:in `new_message_ids'
        from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mail_room-0.3.0/lib/mail_room/mailbox_handler.rb:29:in `new_messages'
        from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mail_room-0.3.0/lib/mail_room/mailbox_handler.rb:17:in `process'
        from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mail_room-0.3.0/lib/mail_room/mailbox_watcher.rb:143:in `process_mailbox'
        from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mail_room-0.3.0/lib/mail_room/mailbox_watcher.rb:123:in `block in run'
```

FYI, we are also doing something completely unrelated to mail_room in our application using IMAP, and we also got the EOFError there once (however while fetching, not searching). Might really be an issue with the IMAP lib. Oh and all these errors occured with Gmail.

```
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/imap.rb:1150:in `get_tagged_response': end of file reached (EOFError)
  /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/imap.rb:1150:in `get_tagged_response'
  /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/imap.rb:1210:in `block in send_command'
  /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/imap.rb:1192:in `send_command'
  /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/imap.rb:1363:in `block in fetch_internal'
  /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/imap.rb:1361:in `fetch_internal'
  /home/deploy/.rbenv/versions/2.1.2/lib/ruby/2.1.0/net/imap.rb:800:in `fetch'
```

How about a solution like this: If the exeption is caught, try it again (up to three times)? I could also do that and submit a PR if you want. It's really annoying that you can't really test it though haha, since the error appears "randomly".

**Comment by tpitale** [comment]
Yeah … I think we'll start with a wide rescue and restart … then go narrower to see if we can localize the rescue/retry.

I'll try to get to it this weekend.

**Comment by tbreier** [comment]
Ok great, thank you!

**Comment by tpitale** [comment]
@tbreier @domness I just released v0.3.1. Let me know how that works for you both!

**Comment by domness** [comment]
Thanks very much!

I'll check it out this week.

**Comment by tbreier** [comment]
Looks good, thank you! I assume / hope that the email does not get marked as SEEN before the EOFError occurs.

**Comment by tpitale** [comment]
This error occurs well before that, so I'm pretty darn sure that won't happen.

**Comment by tbreier** [comment]
Oh, yes of course, you are right :)
