### ISSUE TITLE
Incorrectly configured Mailroom uses 100% CPU

### ISSUE THREAD

**Issue by Armada651** [tpitale/mail_room#56]
If the Mailroom can't connect to the mailserver due to an SSL error it will keep attempting to connect to it going so far as to dedicate a CPU core to the task of banging the mailserver.

To be precise, the command `/opt/gitlab/embedded/bin/ruby /opt/gitlab/embedded/bin/bundle exec mail_room -c /var/opt/gitlab/gitlab-rails/etc/mail_room.yml` is using 100% CPU.

My system is Ubuntu Server 14.04 and I am using the omnibus distribution of GitLab.

Here is an excerpt from my mailroom log file:

```
2015-12-05_16:28:10.65112 /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1454:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
2015-12-05_16:28:10.65116 	from /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1454:in `start_tls_session'
2015-12-05_16:28:10.65116 	from /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1047:in `initialize'
2015-12-05_16:28:10.65117 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `new'
2015-12-05_16:28:10.65117 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `imap'
2015-12-05_16:28:10.65118 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:88:in `log_in'
2015-12-05_16:28:10.65121 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:69:in `setup'
2015-12-05_16:28:10.65122 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:132:in `run'
2015-12-05_16:28:10.65123 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `each'
2015-12-05_16:28:10.65123 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `run'
2015-12-05_16:28:10.65124 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/cli.rb:52:in `start'
2015-12-05_16:28:10.65124 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/bin/mail_room:5:in `<top (required)>'
2015-12-05_16:28:10.65125 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/mail_room:23:in `load'
2015-12-05_16:28:10.65125 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/mail_room:23:in `<main>'
2015-12-05_16:28:10.82077 Runit: starting mail_room
2015-12-05_16:28:23.33484 /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1454:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
2015-12-05_16:28:23.33493 	from /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1454:in `start_tls_session'
2015-12-05_16:28:23.33494 	from /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1047:in `initialize'
2015-12-05_16:28:23.33496 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `new'
2015-12-05_16:28:23.33498 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `imap'
2015-12-05_16:28:23.33499 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:88:in `log_in'
2015-12-05_16:28:23.33501 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:69:in `setup'
2015-12-05_16:28:23.33502 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:132:in `run'
2015-12-05_16:28:23.33504 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `each'
2015-12-05_16:28:23.33506 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `run'
2015-12-05_16:28:23.33507 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/cli.rb:52:in `start'
2015-12-05_16:28:23.33509 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/bin/mail_room:5:in `<top (required)>'
2015-12-05_16:28:23.33510 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/mail_room:23:in `load'
2015-12-05_16:28:23.33512 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/mail_room:23:in `<main>'
2015-12-05_16:28:23.51205 Runit: starting mail_room
2015-12-05_16:28:36.27779 /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1454:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
2015-12-05_16:28:36.27782 	from /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1454:in `start_tls_session'
2015-12-05_16:28:36.27783 	from /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1047:in `initialize'
2015-12-05_16:28:36.27783 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `new'
2015-12-05_16:28:36.27783 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `imap'
2015-12-05_16:28:36.27784 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:88:in `log_in'
2015-12-05_16:28:36.27784 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:69:in `setup'
2015-12-05_16:28:36.27785 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:132:in `run'
2015-12-05_16:28:36.27787 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `each'
2015-12-05_16:28:36.27787 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `run'
2015-12-05_16:28:36.27787 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/cli.rb:52:in `start'
2015-12-05_16:28:36.27788 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/bin/mail_room:5:in `<top (required)>'
2015-12-05_16:28:36.27788 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/mail_room:23:in `load'
2015-12-05_16:28:36.27788 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/mail_room:23:in `<main>'
2015-12-05_16:28:36.44894 Runit: starting mail_room
```

Originally reported in https://github.com/gitlabhq/gitlabhq/issues/9891

**Comment by tpitale** [comment]
You might notice that Runit is the one starting (and restarting) mail_room. This is not a mail_room issue. mail_room will crash (and seemingly be restarted by Runit).

Runit should be able to back off restarts if misconfigured … or fail completely.
