### ISSUE TITLE
Error: `require': cannot load such file -- charlock_holmes

### ISSUE THREAD

**Issue by brovikov** [tpitale/mail_room#57]
After update to last version 0.6.1 - got an error ***cannot load such file -- charlock_holmes***. 
It works if I manually add `charlock_holmes` gem to my `Gemfile`. Anybody know why I lost dependency? 

```
/home/alexey/.rvm/gems/ruby-2.2.2@partsable/gems/mail_room-0.6.1/lib/mail_room/delivery/sidekiq.rb:4:in `require': cannot load such file -- charlock_holmes (LoadError)
	from /home/alexey/.rvm/gems/ruby-2.2.2@partsable/gems/mail_room-0.6.1/lib/mail_room/delivery/sidekiq.rb:4:in `<top (required)>'
	from /home/alexey/.rvm/gems/ruby-2.2.2@partsable/gems/mail_room-0.6.1/lib/mail_room/delivery.rb:4:in `require_relative'
	from /home/alexey/.rvm/gems/ruby-2.2.2@partsable/gems/mail_room-0.6.1/lib/mail_room/delivery.rb:4:in `[]'
	from /home/alexey/.rvm/gems/ruby-2.2.2@partsable/gems/mail_room-0.6.1/lib/mail_room/mailbox.rb:50:in `delivery_klass'
	from /home/alexey/.rvm/gems/ruby-2.2.2@partsable/gems/mail_room-0.6.1/lib/mail_room/mailbox.rb:58:in `delivery'
	from /home/alexey/.rvm/gems/ruby-2.2.2@partsable/gems/mail_room-0.6.1/lib/mail_room/mailbox.rb:75:in `deliver'
	from /home/alexey/.rvm/gems/ruby-2.2.2@partsable/gems/mail_room-0.6.1/lib/mail_room/mailbox_handler.rb:19:in `block in process'
	from /home/alexey/.rvm/gems/ruby-2.2.2@partsable/gems/mail_room-0.6.1/lib/mail_room/mailbox_handler.rb:17:in `each'
	from /home/alexey/.rvm/gems/ruby-2.2.2@partsable/gems/mail_room-0.6.1/lib/mail_room/mailbox_handler.rb:17:in `process'
	from /home/alexey/.rvm/gems/ruby-2.2.2@partsable/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:166:in `process_mailbox'
	from /home/alexey/.rvm/gems/ruby-2.2.2@partsable/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:146:in `block in run'
```

**Comment by tpitale** [comment]
It's not a lost dependency, it's a new dependency for certain delivery methods to handle UTF-8.

I'll update the docs if it's not already in there.

**Comment by tpitale** [comment]
Specifically the sidekiq delivery method.

**Comment by brovikov** [comment]
@tpitale I've got it, thanks!
