### ISSUE TITLE
Raise a configuration error if required fields are missing on a mailbox

### ISSUE THREAD

**Issue by tpitale** [tpitale/mail_room#71]
In the `validate!` for a mailbox we should check for required fields like `name`. Raise a `ConfigurationError` otherwise.

**Comment by tpitale** [comment]
Currently, missing required fields on a mailbox will do weird things like:

```
/Users/tpitale/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/imap.rb:1171:in `get_tagged_response':  Unknown Mailbox: NIL (Failure) (Net::IMAP::NoResponseError)
	from /Users/tpitale/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/imap.rb:1225:in `block in send_command'
	from /Users/tpitale/.rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/tpitale/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/imap.rb:1207:in `send_command'
	from /Users/tpitale/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/imap.rb:453:in `block in select'
	from /Users/tpitale/.rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/tpitale/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/imap.rb:451:in `select'
	from /Users/tpitale/Development/Personal/OSS/mail_room/lib/mail_room/mailbox_watcher.rb:95:in `set_mailbox'
	from /Users/tpitale/Development/Personal/OSS/mail_room/lib/mail_room/mailbox_watcher.rb:70:in `setup'
	from /Users/tpitale/Development/Personal/OSS/mail_room/lib/mail_room/mailbox_watcher.rb:121:in `run'
	from /Users/tpitale/Development/Personal/OSS/mail_room/lib/mail_room/coordinator.rb:19:in `each'
	from /Users/tpitale/Development/Personal/OSS/mail_room/lib/mail_room/coordinator.rb:19:in `run'
	from /Users/tpitale/Development/Personal/OSS/mail_room/lib/mail_room/cli.rb:52:in `start'
```

If possible, we should detect these early during start up and provide a helpful message rather than a confusing stack trace.
