### ISSUE TITLE
Mailroom crash on lost connection to IMAP

### ISSUE THREAD

**Issue by Delagen** [tpitale/mail_room#82]
https://gitlab.com/gitlab-org/gitlab-ce/issues/50842
```
bundler: failed to load command: mail_room (/home/git/gitlab/vendor/bundle/ruby/2.4.0/bin/mail_room)
Net::IMAP::ByeResponseError: AXIGEN Proxy front1 IMAP4rev1: cannot connect to AXIGEN
  /usr/local/lib/ruby/2.4.0/net/imap.rb:1188:in `get_tagged_response'
  /usr/local/lib/ruby/2.4.0/net/imap.rb:1248:in `block in send_command'
  /usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
  /usr/local/lib/ruby/2.4.0/net/imap.rb:1230:in `send_command'
  /usr/local/lib/ruby/2.4.0/net/imap.rb:434:in `login'
  /home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/mail_room-0.9.1/lib/mail_room/connection.rb:84:in `log_in'
  /home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/mail_room-0.9.1/lib/mail_room/connection.rb:68:in `setup'
  /home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/mail_room-0.9.1/lib/mail_room/connection.rb:54:in `rescue in wait'
  /home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/mail_room-0.9.1/lib/mail_room/connection.rb:44:in `wait'
  /home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/mail_room-0.9.1/lib/mail_room/mailbox_watcher.rb:34:in `block in run'
```

**Comment by tpitale** [comment]
This is by design. There are many, many reasons for errors and some in ways that we can't really handle without missing mail or folks want different restart behaviors. MailRoom is intended to be managed and restarted by an external process like init/upstart/etc that is explicitly designed for this purpose.

**Comment by tpitale** [comment]
From the gitlab issue:
> In an Omnibus GitLab installation, mail_room would automatically be restated, so this probably only affects source installations.

**Comment by tpitale** [comment]
I could make the language in this section more clear if that would be helpful: https://github.com/tpitale/mail_room#running-in-production
